name: kora_messenger
description: Kora Messenger — a premium messaging app for seamless communication.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  http: ^1.2.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.2.0
  path_provider: ^2.1.0
  share_plus: ^7.2.0
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/kora_icon.png
    - assets/images/kora_logo_lockup.png
    - assets/images/world_map_glow.png
    - assets/images/kora_support_avatar.png
    - assets/images/kora_ai_avatar.png
    - assets/icons/icon_default_circle.png
    - assets/icons/icon_aurora_circle.png
    - assets/icons/icon_gold_elite.png
