name: kora_messenger
description: Kora Messenger — a premium messaging app for seamless communication.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  file_picker: ^10.0.0
  http: ^1.2.0
  shared_preferences: ^2.2.0
  device_info_plus: ^10.1.0
  android_id: ^0.5.2+1
  url_launcher: ^6.2.0
  path_provider: ^2.1.0
  share_plus: ^10.0.1
  local_auth: ^3.0.2
  qr_flutter: ^4.1.0
  permission_handler: ^12.0.0
  record: ^5.1.0
  flutter_contacts: 2.3.1
  audio_session: ^0.2.3
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^20.0.0
  mobile_scanner: ^7.0.0
  screen_brightness: ^1.0.1
  connectivity_plus: ^7.0.0
  just_audio: ^0.10.6
  audioplayers: ^6.1.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0
  flutter_webrtc: ^1.0.0
  webview_flutter: ^4.10.0
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/kora_icon.webp
    - assets/badges/official_badge.webp
    - assets/badges/premium_badge.webp
    - assets/images/kora_logo_lockup.webp
    - assets/images/world_map_glow.webp
    - assets/images/kora_support_avatar.webp
    - assets/images/kora_ai_avatar.webp
    - assets/icons/icon_default_circle.webp
    - assets/icons/icon_aurora_circle.webp
    - assets/icons/icon_gold_elite.webp
    - assets/wallpapers/cosmic_swirl.webp
    - assets/wallpapers/white_horse_snow.webp
    - assets/wallpapers/palm_leaf.webp
    - assets/wallpapers/moon_in_hand.webp
    - assets/wallpapers/otters_umbrella.webp
    - assets/wallpapers/forest_squirrels.webp
    - assets/wallpapers/polished_pebbles.webp
    - assets/wallpapers/blue_pink_waves.webp
    - assets/wallpapers/terracotta_shapes.webp
    - assets/wallpapers/rose_petals.webp
    - assets/wallpapers/butterfly_flower.webp
    - assets/wallpapers/pink_tulip.webp
    - assets/wallpapers/red_dahlia.webp
    - assets/wallpapers/rainbow_tulip_splash.webp
    - assets/wallpapers/glowing_dress_woman.webp
    - assets/wallpapers/autumn_leaves.webp
    - assets/wallpapers/colorful_3d_balls.webp
    - assets/wallpapers/black_z_gradient.webp
    - assets/wallpapers/kora_default_doodle_milk.webp
    - assets/sounds/
    - assets/wallpapers/kora_default_pro.webp
