allprojects {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            if (project.android.namespace == null) {
                project.android.namespace = project.group.toString() + "." + project.name.toString().replace("-", "_").replace(":", "_")
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
