import 'dart:convert';
import 'chat_models.dart';

/// Message type — text, image, voice, file, system.
enum KoraMessageType {
  text,
  image,
  video,
  videoNote, // WhatsApp-style circular video message
  voice,
  file,
  sticker, // sticker messages (large emoji rendered as stickers)
  system, // date separators, inline notices
  document, // document/file attachments
  contact, // shared contact (vCard)
  location, // shared location
  action, // messages with an action button (e.g. "Subscribe to Kora Premium")
  issueList, // support AI showing a list of common issues to pick from
}

/// A single message in a Kora conversation.
/// Parses reactions from JSON — supports both old single 'reaction' string
/// and new 'reactions' list for backward compatibility.
List<String> _parseReactions(Map<String, dynamic> j) {
  final reactionsList = j['reactions'] as List?;
  if (reactionsList != null) {
    return reactionsList.cast<String>();
  }
  // Fall back to old single-reaction format
  final single = j['reaction'] as String?;
  return single != null ? [single] : [];
}

class KoraMessage {
  final String id;
  final String text;
  final DateTime timestamp;
  final bool isMe; // true = outgoing, false = incoming
  final KoraMessageType type;
  final MessageStatus status;
  final String? replyToId; // if this is a reply
  final String? replyToText;
  final String? replyToName;
  final KoraMessageType? replyToType; // type of the replied-to message for media icon
  /// Emoji reactions on this message. Free users: 1 max. Premium: up to 3.
  final List<String> reactions;

  /// Backward-compat: single reaction accessor. Returns first reaction or null.
  String? get reaction => reactions.isEmpty ? null : reactions.first;
  final String? voiceDuration; // "0:12" etc, for voice messages
  final String? voiceFilePath; // local file path for real audio playback

  /// Remote URL for received voice notes that haven't been downloaded
  /// to the device yet. When set, the bubble shows a download button
  /// instead of play. Once downloaded, the file is cached locally and
  /// [voiceFilePath] is used for playback.
  final String? voiceFileUrl;

  /// Whether an INCOMING voice note has been played by the user.
  /// Outgoing notes are always considered "played" by the sender.
  /// Drives the unplayed indicator dot on the voice bubble.
  final bool isVoicePlayed;

  /// When [status] is [MessageStatus.pendingOffline], tracks whether
  /// an upload attempt is in flight or has been cancelled/failed.
  /// Ignored once the message actually sends.
  final VoiceTransferState voiceTransferState;
  final String? voiceTranscript; // on-device STT transcript
  final String? attachmentName; // for file messages

  /// For [KoraMessageType.action] messages — the button label
  /// (e.g. "Subscribe to Kora Premium") and an action identifier
  /// the bubble uses to route the tap (e.g. 'subscribe_premium').
  final String? actionLabel;
  final String? actionType;

  /// For [KoraMessageType.issueList] messages — a list of common
  /// issues the user can tap to get guided troubleshooting.
  /// Each entry is {id, label}.
  final List<IssueOption>? issueOptions;

  /// Marks messages generated by Kora's AI assistants so the bubble
  /// can show a subtle "AI" indicator if needed.
  final bool isAi;

  /// Whether this AI response used web search (deep search).
  /// Shows a "🔍 Searched the web" badge on the bubble.
  final bool isWebSearch;

  /// Whether an INCOMING message (isMe=false) has been viewed by the
  /// user in this chat. Drives the home screen's unread badge/count.
  /// Outgoing messages (isMe=true) are always considered seen — this
  /// field is only meaningful for incoming messages.
  final bool isSeen;

  /// Whether the user has starred this message. Currently only
  /// affects the "Clear starred messages" option in the Clear Chat
  /// dialog — starring itself isn't exposed in the UI yet.
  final bool isStarred;

  /// For voice messages translated by the SENDER before sending —
  /// the language code/name the note was translated to. When set,
  /// [voiceFilePath] points to the TRANSLATED audio (the recipient
  /// hears the translation, not the original recording) and
  /// [voiceTranscript] holds the translated text.
  final String? translatedLanguageCode;
  final String? translatedLanguageName;

  /// When true, this voice note self-destructs after the recipient
  /// plays it once. The bubble shows a clock badge and the audio is
  /// deleted from both devices after the first playback completes.
  final bool isPlayOnce;

  /// Translated text for this message — persisted on the message record
  /// so it doesn't need to be re-translated every time the chat is opened.
  /// Mirrors WhatsApp's `translated_text` column in the message table.
  ///
  /// When non-null, the message bubble shows the translation below the
  /// original text. Set by [MessageService.translateMessage].
  /// Uses [translatedLanguageCode]/[translatedLanguageName] to track
  /// which language the translation is in.
  final String? translatedText;

  /// Local file path for the media file
  final String? mediaPath;

  /// Remote URL for received media that hasn't been downloaded
  final String? mediaUrl;

  /// Optional caption shown below the media in the bubble
  final String? mediaCaption;

  /// View-once media that self-destructs after viewing
  final bool isViewOnce;

  /// Original width for aspect ratio
  final double? mediaWidth;

  /// Original height for aspect ratio
  final double? mediaHeight;

  /// Duration in seconds for videos
  final int? mediaDuration;

  /// Thumbnail for video messages
  final String? mediaThumbnailPath;

  /// Whether an incoming view-once media has been viewed
  final bool isMediaPlayed;

  /// Whether this message was forwarded from another chat.
  final bool isForwarded;

  /// Whether this group message mentions @all.
  final bool mentionedAll;

  /// Whether this message was edited by the sender.
  /// Shows a small "edited" label next to the timestamp.
  final bool isEdited;

  /// When the message was last edited.
  final DateTime? editedAt;

  /// Whether this message was deleted for everyone.
  /// Renders as "This message was deleted" in a grey bubble.
  final bool isDeletedForEveryone;

  const KoraMessage({
    required this.id,
    required this.text,
    required this.timestamp,
    required this.isMe,
    this.type = KoraMessageType.text,
    this.status = MessageStatus.none,
    this.replyToId,
    this.replyToText,
    this.replyToName,
    this.replyToType,
    this.reactions = const [],
    this.voiceDuration,
    this.voiceFilePath,
    this.voiceFileUrl,
    this.isVoicePlayed = false,
    this.voiceTransferState = VoiceTransferState.uploading,
    this.voiceTranscript,
    this.attachmentName,
    this.actionLabel,
    this.actionType,
    this.issueOptions,
    this.isAi = false,
    this.isWebSearch = false,
    this.isSeen = false,
    this.isStarred = false,
    this.translatedLanguageCode,
    this.translatedLanguageName,
    this.isPlayOnce = false,
    this.translatedText,
    this.mediaPath,
    this.mediaUrl,
    this.mediaCaption,
    this.isViewOnce = false,
    this.mediaWidth,
    this.mediaHeight,
    this.mediaDuration,
    this.mediaThumbnailPath,
    this.isMediaPlayed = false,
    this.isForwarded = false,
    this.mentionedAll = false,
    this.isEdited = false,
    this.editedAt,
    this.isDeletedForEveryone = false,
  });

  KoraMessage copyWith({
    String? id,
    String? text,
    DateTime? timestamp,
    bool? isMe,
    KoraMessageType? type,
    MessageStatus? status,
    String? replyToId,
    String? replyToText,
    String? replyToName,
    List<String>? reactions,
    String? voiceDuration,
    String? voiceFilePath,
    String? voiceFileUrl,
    bool? isVoicePlayed,
    VoiceTransferState? voiceTransferState,
    String? voiceTranscript,
    String? attachmentName,
    String? actionLabel,
    String? actionType,
    List<IssueOption>? issueOptions,
    bool? isAi,
    bool? isWebSearch,
    bool? isSeen,
    bool? isStarred,
    String? translatedLanguageCode,
    String? translatedLanguageName,
    bool? isPlayOnce,
    String? translatedText,
    String? mediaPath,
    String? mediaUrl,
    String? mediaCaption,
    bool? isViewOnce,
    double? mediaWidth,
    double? mediaHeight,
    int? mediaDuration,
    String? mediaThumbnailPath,
    bool? isMediaPlayed,
    bool? isForwarded,
    bool? mentionedAll,
    bool? isEdited,
    DateTime? editedAt,
    bool? isDeletedForEveryone,
  }) {
    return KoraMessage(
      id: id ?? this.id,
      text: text ?? this.text,
      timestamp: timestamp ?? this.timestamp,
      isMe: isMe ?? this.isMe,
      type: type ?? this.type,
      status: status ?? this.status,
      replyToId: replyToId ?? this.replyToId,
      replyToText: replyToText ?? this.replyToText,
      replyToName: replyToName ?? this.replyToName,
      replyToType: replyToType ?? this.replyToType,
      reactions: reactions ?? this.reactions,
      voiceDuration: voiceDuration ?? this.voiceDuration,
      voiceFilePath: voiceFilePath ?? this.voiceFilePath,
      voiceFileUrl: voiceFileUrl ?? this.voiceFileUrl,
      isVoicePlayed: isVoicePlayed ?? this.isVoicePlayed,
      voiceTransferState: voiceTransferState ?? this.voiceTransferState,
      voiceTranscript: voiceTranscript ?? this.voiceTranscript,
      attachmentName: attachmentName ?? this.attachmentName,
      actionLabel: actionLabel ?? this.actionLabel,
      actionType: actionType ?? this.actionType,
      issueOptions: issueOptions ?? this.issueOptions,
      isAi: isAi ?? this.isAi,
      isWebSearch: isWebSearch ?? this.isWebSearch,
      isSeen: isSeen ?? this.isSeen,
      isStarred: isStarred ?? this.isStarred,
      translatedLanguageCode: translatedLanguageCode ?? this.translatedLanguageCode,
      translatedLanguageName: translatedLanguageName ?? this.translatedLanguageName,
      isPlayOnce: isPlayOnce ?? this.isPlayOnce,
      translatedText: translatedText ?? this.translatedText,
      mediaPath: mediaPath ?? this.mediaPath,
      mediaUrl: mediaUrl ?? this.mediaUrl,
      mediaCaption: mediaCaption ?? this.mediaCaption,
      isViewOnce: isViewOnce ?? this.isViewOnce,
      mediaWidth: mediaWidth ?? this.mediaWidth,
      mediaHeight: mediaHeight ?? this.mediaHeight,
      mediaDuration: mediaDuration ?? this.mediaDuration,
      mediaThumbnailPath: mediaThumbnailPath ?? this.mediaThumbnailPath,
      isMediaPlayed: isMediaPlayed ?? this.isMediaPlayed,
      isForwarded: isForwarded ?? this.isForwarded,
      mentionedAll: mentionedAll ?? this.mentionedAll,
      isEdited: isEdited ?? this.isEdited,
      editedAt: editedAt ?? this.editedAt,
      isDeletedForEveryone: isDeletedForEveryone ?? this.isDeletedForEveryone,
    );
  }

  /// Serialise to JSON for persistence in SharedPreferences.
  Map<String, dynamic> toJson() => {
    'id': id,
    'text': text,
    'ts': timestamp.toIso8601String(),
    'me': isMe,
    'type': type.name,
    'status': status.name,
    'replyToId': replyToId,
    'replyToText': replyToText,
    'replyToName': replyToName,
    'replyToType': replyToType?.name,
    'reactions': reactions,
    'reaction': reaction, // backward compat
    'voiceDuration': voiceDuration,
    'voiceFilePath': voiceFilePath,
    'voiceFileUrl': voiceFileUrl,
    'isVoicePlayed': isVoicePlayed,
    'voiceTransferState': voiceTransferState.name,
    'voiceTranscript': voiceTranscript,
    'attachmentName': attachmentName,
    'actionLabel': actionLabel,
    'actionType': actionType,
    'issueOptions': issueOptions?.map((e) => e.toJson()).toList(),
    'isAi': isAi,
    'isWebSearch': isWebSearch,
    'isSeen': isSeen,
    'isStarred': isStarred,
    'translatedLanguageCode': translatedLanguageCode,
    'translatedLanguageName': translatedLanguageName,
    'isPlayOnce': isPlayOnce,
    'translatedText': translatedText,
    'mediaPath': mediaPath,
    'mediaUrl': mediaUrl,
    'mediaCaption': mediaCaption,
    'isViewOnce': isViewOnce,
    'mediaWidth': mediaWidth,
    'mediaHeight': mediaHeight,
    'mediaDuration': mediaDuration,
    'mediaThumbnailPath': mediaThumbnailPath,
    'isMediaPlayed': isMediaPlayed,
    'isForwarded': isForwarded,
    'mentionedAll': mentionedAll,
    'isEdited': isEdited,
    'editedAt': editedAt?.toIso8601String(),
    'isDeletedForEveryone': isDeletedForEveryone,
  };

  /// Deserialise from JSON.
  factory KoraMessage.fromJson(Map<String, dynamic> j) => KoraMessage(
    id: j['id'] as String,
    text: j['text'] as String? ?? '',
    timestamp: DateTime.parse(j['ts'] as String),
    isMe: j['me'] as bool? ?? false,
    type: KoraMessageType.values.firstWhere(
      (e) => e.name == j['type'],
      orElse: () => KoraMessageType.text,
    ),
    status: MessageStatus.values.firstWhere(
      (e) => e.name == j['status'],
      orElse: () => MessageStatus.none,
    ),
    replyToId: j['replyToId'] as String?,
    replyToText: j['replyToText'] as String?,
    replyToName: j['replyToName'] as String?,
    replyToType: (j['replyToType'] as String?) != null ? KoraMessageType.values.byName(j['replyToType']!) : null,
    reactions: _parseReactions(j),
    voiceDuration: j['voiceDuration'] as String?,
    voiceFilePath: j['voiceFilePath'] as String?,
    voiceFileUrl: j['voiceFileUrl'] as String?,
    isVoicePlayed: j['isVoicePlayed'] as bool? ?? false,
    voiceTransferState: VoiceTransferState.values.firstWhere(
      (e) => e.name == j['voiceTransferState'],
      orElse: () => VoiceTransferState.uploading,
    ),
    voiceTranscript: j['voiceTranscript'] as String?,
    attachmentName: j['attachmentName'] as String?,
    actionLabel: j['actionLabel'] as String?,
    actionType: j['actionType'] as String?,
    issueOptions: (j['issueOptions'] as List?)
        ?.map((e) => IssueOption.fromJson(e as Map<String, dynamic>))
        .toList(),
    isAi: j['isAi'] as bool? ?? false,
    isWebSearch: j['isWebSearch'] as bool? ?? false,
    isSeen: j['isSeen'] as bool? ?? true,
    isStarred: j['isStarred'] as bool? ?? false,
    translatedLanguageCode: j['translatedLanguageCode'] as String?,
    translatedLanguageName: j['translatedLanguageName'] as String?,
    isPlayOnce: j['isPlayOnce'] as bool? ?? false,
    translatedText: j['translatedText'] as String?,
    mediaPath: j['mediaPath'] as String?,
    mediaUrl: j['mediaUrl'] as String?,
    mediaCaption: j['mediaCaption'] as String?,
    isViewOnce: j['isViewOnce'] as bool? ?? false,
    mediaWidth: (j['mediaWidth'] as num?)?.toDouble(),
    mediaHeight: (j['mediaHeight'] as num?)?.toDouble(),
    mediaDuration: j['mediaDuration'] as int?,
    mediaThumbnailPath: j['mediaThumbnailPath'] as String?,
    isMediaPlayed: j['isMediaPlayed'] as bool? ?? false,
    isForwarded: j['isForwarded'] as bool? ?? false,
    mentionedAll: j['mentionedAll'] as bool? ?? false,
    isEdited: j['isEdited'] as bool? ?? false,
    editedAt: j['editedAt'] != null ? DateTime.parse(j['editedAt'] as String) : null,
    isDeletedForEveryone: j['isDeletedForEveryone'] as bool? ?? false,
  );

  /// Estimated on-disk size of this message in bytes — used to show
  /// "Clear chat (X kB)" in the Clear Chat dialog. Text is measured
  /// exactly (UTF-8 byte length); media types use realistic average
  /// sizes since real file attachments aren't wired up yet.
  int get estimatedSizeBytes {
    switch (type) {
      case KoraMessageType.voice:
        final parts = (voiceDuration ?? '0:00').split(':');
        final mins = parts.length > 1 ? (int.tryParse(parts[0]) ?? 0) : 0;
        final secs = int.tryParse(parts.length > 1 ? parts[1] : parts[0]) ?? 0;
        final totalSecs = (mins * 60 + secs).clamp(1, 600);
        return totalSecs * 2000; // ~2 KB/sec for a compressed voice note
      case KoraMessageType.image:
        return 180000; // ~180 KB average compressed photo
      case KoraMessageType.video:
        return 2500000; // ~2.5 MB average video
      case KoraMessageType.file:
        return attachmentName != null ? 350000 : 100000;
      case KoraMessageType.sticker:
        return 256; // sticker is a single emoji character
      case KoraMessageType.system:
      case KoraMessageType.action:
      case KoraMessageType.issueList:
        return 0;
      case KoraMessageType.document:
        return 100000;
      case KoraMessageType.contact:
        return 512;
      case KoraMessageType.location:
        return 256;
      case KoraMessageType.text:
        return utf8.encode(text).length + 32; // text bytes + metadata overhead
    }
  }
}

/// A single tappable issue in a [KoraMessageType.issueList] message.
class IssueOption {
  final String id;
  final String label;

  const IssueOption({required this.id, required this.label});

  Map<String, dynamic> toJson() => {'id': id, 'label': label};

  factory IssueOption.fromJson(Map<String, dynamic> j) => IssueOption(
    id: j['id'] as String,
    label: j['label'] as String,
  );
}
