import 'chat_models.dart';

/// Message type — text, image, voice, file, system.
enum KoraMessageType {
  text,
  image,
  voice,
  file,
  system, // date separators, inline notices
  action, // messages with an action button (e.g. "Subscribe to Kora Premium")
}

/// A single message in a Kora conversation.
class KoraMessage {
  final String id;
  final String text;
  final DateTime timestamp;
  final bool isMe; // true = outgoing, false = incoming
  final KoraMessageType type;
  final MessageStatus status;
  final String? replyToId; // if this is a reply
  final String? replyToText;
  final String? replyToName;
  final String? reaction; // emoji reaction (single for now)
  final String? voiceDuration; // "0:12" etc, for voice messages
  final String? attachmentName; // for file messages

  /// For [KoraMessageType.action] messages — the button label
  /// (e.g. "Subscribe to Kora Premium") and an action identifier
  /// the bubble uses to route the tap (e.g. 'subscribe_premium').
  final String? actionLabel;
  final String? actionType;

  /// Marks messages generated by Kora's AI assistants so the bubble
  /// can show a subtle "AI" indicator if needed.
  final bool isAi;

  const KoraMessage({
    required this.id,
    required this.text,
    required this.timestamp,
    required this.isMe,
    this.type = KoraMessageType.text,
    this.status = MessageStatus.none,
    this.replyToId,
    this.replyToText,
    this.replyToName,
    this.reaction,
    this.voiceDuration,
    this.attachmentName,
    this.actionLabel,
    this.actionType,
    this.isAi = false,
  });

  KoraMessage copyWith({
    String? id,
    String? text,
    DateTime? timestamp,
    bool? isMe,
    KoraMessageType? type,
    MessageStatus? status,
    String? replyToId,
    String? replyToText,
    String? replyToName,
    String? reaction,
    String? voiceDuration,
    String? attachmentName,
    String? actionLabel,
    String? actionType,
    bool? isAi,
  }) {
    return KoraMessage(
      id: id ?? this.id,
      text: text ?? this.text,
      timestamp: timestamp ?? this.timestamp,
      isMe: isMe ?? this.isMe,
      type: type ?? this.type,
      status: status ?? this.status,
      replyToId: replyToId ?? this.replyToId,
      replyToText: replyToText ?? this.replyToText,
      replyToName: replyToName ?? this.replyToName,
      reaction: reaction ?? this.reaction,
      voiceDuration: voiceDuration ?? this.voiceDuration,
      attachmentName: attachmentName ?? this.attachmentName,
      actionLabel: actionLabel ?? this.actionLabel,
      actionType: actionType ?? this.actionType,
      isAi: isAi ?? this.isAi,
    );
  }

  /// Serialise to JSON for persistence in SharedPreferences.
  Map<String, dynamic> toJson() => {
    'id': id,
    'text': text,
    'ts': timestamp.toIso8601String(),
    'me': isMe,
    'type': type.name,
    'status': status.name,
    'replyToId': replyToId,
    'replyToText': replyToText,
    'replyToName': replyToName,
    'reaction': reaction,
    'voiceDuration': voiceDuration,
    'attachmentName': attachmentName,
    'actionLabel': actionLabel,
    'actionType': actionType,
    'isAi': isAi,
  };

  /// Deserialise from JSON.
  factory KoraMessage.fromJson(Map<String, dynamic> j) => KoraMessage(
    id: j['id'] as String,
    text: j['text'] as String? ?? '',
    timestamp: DateTime.parse(j['ts'] as String),
    isMe: j['me'] as bool? ?? false,
    type: KoraMessageType.values.firstWhere(
      (e) => e.name == j['type'],
      orElse: () => KoraMessageType.text,
    ),
    status: MessageStatus.values.firstWhere(
      (e) => e.name == j['status'],
      orElse: () => MessageStatus.none,
    ),
    replyToId: j['replyToId'] as String?,
    replyToText: j['replyToText'] as String?,
    replyToName: j['replyToName'] as String?,
    reaction: j['reaction'] as String?,
    voiceDuration: j['voiceDuration'] as String?,
    attachmentName: j['attachmentName'] as String?,
    actionLabel: j['actionLabel'] as String?,
    actionType: j['actionType'] as String?,
    isAi: j['isAi'] as bool? ?? false,
  );
}
